:construction_worker: try to fix error.

diff --git a/.github/workflows/ubuntu.yml b/.github/workflows/ubuntu.yml
--- a/.github/workflows/ubuntu.yml
+++ b/.github/workflows/ubuntu.yml
@@ -75,9 +75,14 @@ jobs:
             qtdeclarative5-dev \
             libqt5svg5-dev \
             libqt5charts5-dev \
-            libqt5uitools5-dev \
+            qttools5-dev \
             qt5-qmake \
             qtbase5-dev-tools
+
+      - name: Verify Qt5UiTools Installation
+        run: |
+          dpkg -l | grep qttools5-dev || echo "qttools5-dev not installed"
+          ls /usr/lib/$(uname -m)-linux-gnu/cmake/Qt5UiTools/Qt5UiToolsConfig.cmake || echo "Qt5UiToolsConfig.cmake not found"
 
       - name: Clone Repository
         uses: actions/checkout@v4
@@ -85,7 +90,6 @@ jobs:
           submodules: recursive
 
       - name: Setup ccache
-        # ccache is not supported on ARM yet
         if: matrix.os != 'ubuntu-24.04-arm'
         uses: hendrikmuhs/ccache-action@v1.2
         with:
@@ -99,25 +103,35 @@ jobs:
 
       - name: Configure CMake (Debug)
         working-directory: ${{github.workspace}}/build_debug
-        run: >
-          cmake ${{github.workspace}}
-          -DCMAKE_CXX_COMPILER=${{matrix.compiler}}
-          -DCMAKE_BUILD_TYPE=Debug
+        run: |
+          cmake ${{github.workspace}} \
+            -DCMAKE_CXX_COMPILER=${{matrix.compiler}} \
+            -DCMAKE_BUILD_TYPE=Debug \
+            -DCMAKE_VERBOSE_MAKEFILE=ON
 
-      - name: Build and test (Debug)
+      - name: Build (Debug)
         working-directory: ${{github.workspace}}/build_debug
         run: cmake --build . --config Debug -j4
+
+      - name: Test (Debug)
+        working-directory: ${{github.workspace}}/build_debug
+        run: ctest -C Debug --verbose --output-on-failure --repeat until-pass:3 --parallel 4
 
       - name: Create Build Environment (Release)
         run: cmake -E make_directory ${{github.workspace}}/build_release
 
       - name: Configure CMake (Release)
         working-directory: ${{github.workspace}}/build_release
-        run: >
-          cmake ${{github.workspace}}
-          -DCMAKE_CXX_COMPILER=${{matrix.compiler}}
-          -DCMAKE_BUILD_TYPE=Release
+        run: |
+          cmake ${{github.workspace}} \
+            -DCMAKE_CXX_COMPILER=${{matrix.compiler}} \
+            -DCMAKE_BUILD_TYPE=Release \
+            -DCMAKE_VERBOSE_MAKEFILE=ON
 
-      - name: Build and test (Release)
+      - name: Build (Release)
         working-directory: ${{github.workspace}}/build_release
         run: cmake --build . --config Release -j4
+
+      - name: Test (Release)
+        working-directory: ${{github.workspace}}/build_release
+        run: ctest -C Release --verbose --output-on-failure --repeat until-pass:3 --parallel 4
